### ISSUE TITLE
项目相关问题

### ISSUE THREAD

**Issue by zcker** [rmfish/tutake#6]
大佬，正好目前有这方面的需求，想向你学习一下，能不能加个微信交流
一是也想出一份力，看看说明文档能不能写的清楚点，或者哪个地方功能完善一下
二是没有tushare的账号，想跟大佬出点钱买一下api更新下数据
也希望和大佬学习一下
我的微信是chengkai__zhang，谢谢

**Comment by zcker** [comment]
想问一下大佬，在windows上怎么部署呢？只对于linux做了适配吗？

**Comment by rmfish** [comment]
> 如果使用过程中有问题有bug，可以随时提交issue，也欢迎提交pr。 tushare的账号这个比较敏感，还是不太鼓励分享使用，但是目前的系统是支持多个账号并行跑的（解决并发限流的限制），账号的问题还需要你自己想办法解决了。

**Comment by rmfish** [comment]
> 

如果你需要历史的数据，我想办法做个历史数据的打包文件，共享出来

**Comment by zcker** [comment]
![image](https://user-images.githubusercontent.com/45120415/210940966-7ad9b4ab-74f6-46a4-bc11-97f6db370ef0.png)
self.config_dir这个值没有设置，我手动设置好之后
![image](https://user-images.githubusercontent.com/45120415/210941055-1f3eb9e7-9348-4697-9a31-629e3478ec7e.png)
![image](https://user-images.githubusercontent.com/45120415/210941147-f271b3e4-03ed-4115-8bfd-e206a5daa523.png)
设置好之后出了这个问题
这个项目的引用实在有点复杂，不清楚怎么排查了
那麻烦大佬再把readme写的细节一点，不清楚怎么并行账号

**Comment by rmfish** [comment]
> ![image](https://user-images.githubusercontent.com/45120415/210940966-7ad9b4ab-74f6-46a4-bc11-97f6db370ef0.png) self.config_dir这个值没有设置，我手动设置好之后 ![image](https://user-images.githubusercontent.com/45120415/210941055-1f3eb9e7-9348-4697-9a31-629e3478ec7e.png) ![image](https://user-images.githubusercontent.com/45120415/210941147-f271b3e4-03ed-4115-8bfd-e206a5daa523.png) 设置好之后出了这个问题 这个项目的引用实在有点复杂，不清楚怎么排查了 那麻烦大佬再把readme写的细节一点，不清楚怎么并行账号

这的确是个bug，你可以先把配置文件中logger的配置项删除(tutake.logging.config_file)，使用默认的logger配置

**Comment by rmfish** [comment]
多个账号并行的配置：
tushare:
  tokens:
    5000:
      - xxx
      - xxx
    2000:
       - xxx
      - xxx
 每行一个对应积分的账号，这样运行时遇到一个账号限流就会选下一个继续执行

**Comment by rmfish** [comment]
日志bug 已经修复，如果存在其他bug，新建issue。
如果有其他的问题，到Discussions中讨论
